# TP4 | INF8808

In this notebook, we will start by creating a simple app to help explore our data. This step is important in conceiving data visualizations. It helps to determine which type of data visualization is appropriate for our data set, as well as which features we'd like to include. 

In the rest of this notebook, you will have to complete some cells to prepare for the implementation of an animated bubble chart in the next steps. 

To begin, take a look at the following cells, where we complete the necessary imports and load the data.

In [1]:
import pandas as pd
import json

In [2]:
with open('../src/assets/data/countriesData.json') as data_file:    
    data = json.load(data_file)  

df_2000 = pd.json_normalize(data, '2000')
df_2015 = pd.json_normalize(data, '2015')

In [3]:
!pip install jupyter-dash

Requirement already satisfied: jupyter-dash in c:\python311\lib\site-packages (0.4.2)
Requirement already satisfied: dash in c:\python311\lib\site-packages (from jupyter-dash) (2.6.2)
Requirement already satisfied: requests in c:\python311\lib\site-packages (from jupyter-dash) (2.32.3)
Requirement already satisfied: flask in c:\users\aniss\appdata\roaming\python\python311\site-packages (from jupyter-dash) (2.2.2)
Requirement already satisfied: retrying in c:\python311\lib\site-packages (from jupyter-dash) (1.3.4)
Requirement already satisfied: ipython in c:\users\aniss\appdata\roaming\python\python311\site-packages (from jupyter-dash) (8.29.0)
Requirement already satisfied: ipykernel in c:\users\aniss\appdata\roaming\python\python311\site-packages (from jupyter-dash) (6.29.5)
Requirement already satisfied: ansi2html in c:\python311\lib\site-packages (from jupyter-dash) (1.9.2)
Requirement already satisfied: nest-asyncio in c:\python311\lib\site-packages (from jupyter-dash) (1.6.0)
Requirement already satisfied: flask-compress in c:\python311\lib\site-packages (from dash->jupyter-dash) (1.13)
Requirement already satisfied: plotly>=5.0.0 in c:\python311\lib\site-packages (from dash->jupyter-dash) (5.11.0)
Requirement already satisfied: dash-html-components==2.0.0 in c:\python311\lib\site-packages (from dash->jupyter-dash) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\python311\lib\site-packages (from dash->jupyter-dash) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\python311\lib\site-packages (from dash->jupyter-dash) (5.0.0)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\python311\lib\site-packages (from flask->jupyter-dash) (2.2.2)
Requirement already satisfied: Jinja2>=3.0 in c:\python311\lib\site-packages (from flask->jupyter-dash) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\python311\lib\site-packages (from flask->jupyter-dash) (2.1.2)
Requirement already satisfied: click>=8.0 in c:\python311\lib\site-packages (from flask->jupyter-dash) (8.1.3)
Requirement already satisfied: colorama in c:\python311\lib\site-packages (from click>=8.0->flask->jupyter-dash) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python311\lib\site-packages (from Jinja2>=3.0->flask->jupyter-dash) (2.1.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\python311\lib\site-packages (from plotly>=5.0.0->dash->jupyter-dash) (8.1.0)
Requirement already satisfied: brotli in c:\python311\lib\site-packages (from flask-compress->dash->jupyter-dash) (1.0.9)
Requirement already satisfied: comm>=0.1.1 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (1.8.7)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (0.1.7)
Requirement already satisfied: packaging in c:\python311\lib\site-packages (from ipykernel->jupyter-dash) (23.2)
Requirement already satisfied: psutil in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (6.1.0)
Requirement already satisfied: pyzmq>=24 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (26.2.0)
Requirement already satisfied: tornado>=6.1 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipykernel->jupyter-dash) (5.14.3)
Requirement already satisfied: decorator in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipython->jupyter-dash) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipython->jupyter-dash) (0.19.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipython->jupyter-dash) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipython->jupyter-dash) (2.18.0)
Requirement already satisfied: stack-data in c:\users\aniss\appdata\roaming\python\python311\site-packages (from ipython->jupyter-dash) (0.6.3)
Requirement already satisfied: typing-extensions>=4.6 in c:\python311\lib\site-packages (from ipython->jupyter-dash) (4.10.0)
Requirement already satisfied: wcwidth in c:\python311\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->jupyter-dash) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from jedi>=0.16->ipython->jupyter-dash) (0.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python311\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter-dash) (4.3.6)
Requirement already satisfied: pywin32>=300 in c:\python311\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter-dash) (308)
Requirement already satisfied: six>=1.5 in c:\python311\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel->jupyter-dash) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests->jupyter-dash) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests->jupyter-dash) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests->jupyter-dash) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests->jupyter-dash) (2025.1.31)
Requirement already satisfied: executing>=1.2.0 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from stack-data->ipython->jupyter-dash) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\aniss\appdata\roaming\python\python311\site-packages (from stack-data->ipython->jupyter-dash) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\aniss\appdata\roaming\python\python311\site-packages (from stack-data->ipython->jupyter-dash) (0.2.3)

WARNING: Ignoring invalid distribution ~%p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~-p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~0p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~1p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~2p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~3p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~4p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~5p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~6p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~7p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~8p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~9p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~=p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~%p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~-p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~0p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~1p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~2p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~3p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~4p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~5p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~6p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~7p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~8p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~9p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~=p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~%p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~-p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~0p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~1p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~2p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~3p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~4p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~5p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~6p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~7p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~8p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~9p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~=p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~p (C:\Python311\Lib\site-packages)

In [4]:
from jupyter_dash import JupyterDash
import dash
import dash_html_components as html
import dash_core_components as dcc

import plotly.express as px

C:\Users\aniss\AppData\Local\Temp\ipykernel_22636\3203507159.py:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
C:\Users\aniss\AppData\Local\Temp\ipykernel_22636\3203507159.py:4: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc

In [5]:
external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css']

In [6]:
app = JupyterDash(__name__, external_stylesheets=external_stylesheets)

In [7]:
df_2000

            Country Name           GDP       CO2  Population      Continent
0                Algeria   1764.973830  2.830380    31042235         Africa
1                Andorra  21854.246803  8.019284       65390         Europe
2                 Angola    556.836318  0.581961    16395473         Africa
3                Albania   1126.683318  0.978175     3089027         Europe
4    Antigua and Barbuda  10920.842688  4.534545       76016  North America
..                   ...           ...       ...         ...            ...
169              Vanuatu   1470.572265  0.455966      184972        Oceania
170              Vietnam    390.093326  0.671309    79910412           Asia
171                Yemen    554.448633  0.841075    17409072           Asia
172               Zambia    345.689554  0.174972    10415944         Africa
173             Zimbabwe    563.057741  1.171874    11881477         Africa

[174 rows x 5 columns]

In [8]:
df_2015

            Country Name           GDP       CO2  Population      Continent
0                Albania   3952.801215  1.602648     2880703         Europe
1                Algeria   4177.892515  3.854557    39728025         Africa
2                Andorra  35762.523074  5.969786       78011         Europe
3                 Angola   4166.979684  1.240245    27884381         Africa
4    Antigua and Barbuda  14286.093160  5.839546       93566  North America
..                   ...           ...       ...         ...            ...
169              Vanuatu   2801.939848  0.486896      271130        Oceania
170              Vietnam   2085.101484  2.032108    92677076           Asia
171                Yemen   1395.439633  0.497091    26497889           Asia
172               Zambia   1337.796110  0.285428    15879361         Africa
173             Zimbabwe   1445.071062  0.891624    13814629         Africa

[174 rows x 5 columns]

# Question 1 

You notice that the tables `df_2000` and `df_2015` have columns `GDP` and `CO2`, which you wish to include in your visualization. 

These columns contain numbers with many decimal places, but you are only planning on displaying numbers up to two decimal places in your visualization. 

Round the numbers in these dataframes so they only contain numbers up to two decimal places.

In [9]:
# TODO : Round the values

df_2000 = df_2000.round({'GDP': 2, 'CO2': 2})
df_2015 = df_2015.round({'GDP': 2, 'CO2': 2})

In [10]:
# Use this cell to check your answer
df_2000

            Country Name       GDP   CO2  Population      Continent
0                Algeria   1764.97  2.83    31042235         Africa
1                Andorra  21854.25  8.02       65390         Europe
2                 Angola    556.84  0.58    16395473         Africa
3                Albania   1126.68  0.98     3089027         Europe
4    Antigua and Barbuda  10920.84  4.53       76016  North America
..                   ...       ...   ...         ...            ...
169              Vanuatu   1470.57  0.46      184972        Oceania
170              Vietnam    390.09  0.67    79910412           Asia
171                Yemen    554.45  0.84    17409072           Asia
172               Zambia    345.69  0.17    10415944         Africa
173             Zimbabwe    563.06  1.17    11881477         Africa

[174 rows x 5 columns]

In [11]:
# Use this cell to check your answer
df_2015

            Country Name       GDP   CO2  Population      Continent
0                Albania   3952.80  1.60     2880703         Europe
1                Algeria   4177.89  3.85    39728025         Africa
2                Andorra  35762.52  5.97       78011         Europe
3                 Angola   4166.98  1.24    27884381         Africa
4    Antigua and Barbuda  14286.09  5.84       93566  North America
..                   ...       ...   ...         ...            ...
169              Vanuatu   2801.94  0.49      271130        Oceania
170              Vietnam   2085.10  2.03    92677076           Asia
171                Yemen   1395.44  0.50    26497889           Asia
172               Zambia   1337.80  0.29    15879361         Africa
173             Zimbabwe   1445.07  0.89    13814629         Africa

[174 rows x 5 columns]

# Question 2

Given the data you have, you decide to create a simple scatter plot for each dataframe.

In the next cells, fill the functions to accomplish this task. 

### 2.1

First, fill the `get_scatter` function, which returns a scatter plot figure for the given data frame. Its x axis is GDP and its y axis is CO2. Its `hover_name` property is represented by the country name. The title of the scatter plot is passed as argument. The axes should be represented as linearly scaled.

### 2.2

Second, fill the `get_range` function, which will help to more easily compare the two scatter plots. We want both scatter plots to have the same range for their x and y axes, and to be able to see all the points in each scatter plot. Thus, for the given column, the function should return an array containing the minimum and maximum across the two dataframes.

In [12]:
def get_scatter(df, title):
    fig = px.scatter(df, x="GDP", y="CO2", hover_name="Country Name", title=title)
    fig.update_layout(xaxis_type='linear', yaxis_type='linear')
    return fig

In [13]:
def get_range(col, df1, df2):
    min_val = min([min(df1[col]), min(df2[col])])
    max_val = max([max(df1[col]), max(df2[col])])
    return [min_val, max_val]

Run these next three cells to check your answer. You should see your two scatter plots side by side.

In [14]:
fig_2000 = get_scatter(df_2000, '2000')
fig_2015 = get_scatter(df_2015, '2015')

fig_2000.update_layout(xaxis=dict(range=get_range('GDP', df_2000, df_2015)))
fig_2000.update_layout(yaxis=dict(range=get_range('CO2', df_2000, df_2015)))
fig_2000.update_layout(dragmode=False)


fig_2015.update_layout(xaxis=dict(range=get_range('GDP', df_2000, df_2015)))
fig_2015.update_layout(yaxis=dict(range=get_range('CO2', df_2000, df_2015)))
fig_2015.update_layout(dragmode=False);

In [15]:
config=dict(
                scrollZoom=False,
                showTips=False,
                showAxisDragHandles=False,
                doubleClick=False,
                displayModeBar=False
            )

app.layout = html.Div(children=[
        html.Div(className='row', children=[dcc.Graph(id='fig-2000', figure=fig_2000, className='six columns', config=config), dcc.Graph(id='fig-2015', figure=fig_2015, className='six columns', config=config)]),
        html.Div(style = {'width': '100%', 'display': 'flex', 'alignItems': 'center', 'justifyContent': 'center', 'flexDirection' : 'column'}, children=[
            html.H4('Hover over markers for more information', id='country'),
            html.Table(children=[
                html.Thead(html.Tr(children=[html.Th(), html.Th('GDP per capita ($ USD)'), html.Th('CO2 emissions per capita (metric tonnes)')])),
                html.Tbody(children=[
                    html.Tr(children=[html.Th('2000'), html.Td(id='2000-gdp'), html.Td(id='2000-co2')]),
                    html.Tr(children=[html.Th('2015'), html.Td(id='2015-gdp'), html.Td(id='2015-co2')])
                ])
            ])
        ])
    ])

In [17]:
# Use this cell to check your answer
app.run_server(port=8051)

Dash app running on http://127.0.0.1:8051/

# Question 3

Now that you've seen both charts side-by-side, you've realized it might be interesting to model them with an animation. However, you'd like to be able to compare the data for countries more easily across the scatter plots.

To do so, you will implement a callback function which is triggered whenever a point is hovered in one of the two scatter plots. The signature for this function is already started below. 

Complete the function so that whenever a point is hovered, the appropriate information is displayed in the table below the scatter plots. 

The title of the table should be the name of the country of the hovered point. Further, the table should contain the GDP and CO2 information for the years 2000 and 2015.

In [17]:
from dash.dependencies import Input, Output, State

In [18]:
@app.callback(
    [Output('country', 'children'), Output('2000-gdp', 'children'), Output('2000-co2', 'children'), Output('2015-gdp', 'children'), Output('2015-co2', 'children')],
    [Input('fig-2000', 'hoverData'), Input('fig-2015', 'hoverData')],
    [State('country', 'children'), State('2000-gdp', 'children'), State('2000-co2', 'children'), State('2015-gdp', 'children'), State('2015-co2', 'children')])
def display_selected_data(hoverData2000, hoverData2015, prevCountry, prevgdp0, prevco20, prevgdp5, prevco25):
    # TODO : Handle the display when a point is hovered
    context = dash.callback_context
    trigger_id = context.triggered[0]['prop_id'].split('.')[0] if context.triggered else None

    # default value
    country = prevCountry or "Hover over a point"
    gdp_2000 = prevgdp0 or "-"
    co2_2000 = prevco20 or "-"
    gdp_2015 = prevgdp5 or "-"
    co2_2015 = prevco25 or "-"

    def get_country_data(country_name):
        data_2000 = df_2000[df_2000['Country Name'] == country_name]
        data_2015 = df_2015[df_2015['Country Name'] == country_name]
        gdp0 = data_2000['GDP'].iloc[0] if not data_2000.empty else "-"
        co20 = data_2000['CO2'].iloc[0] if not data_2000.empty else "-"
        gdp5 = data_2015['GDP'].iloc[0] if not data_2015.empty else "-"
        co25 = data_2015['CO2'].iloc[0] if not data_2015.empty else "-"
        return gdp0, co20, gdp5, co25

    if trigger_id == 'fig-2000' and hoverData2000:
        country = hoverData2000['points'][0]['hovertext']
        gdp_2000, co2_2000, gdp_2015, co2_2015 = get_country_data(country)
    elif trigger_id == 'fig-2015' and hoverData2015:
        country = hoverData2015['points'][0]['hovertext']
        gdp_2000, co2_2000, gdp_2015, co2_2015 = get_country_data(country)

    return country, gdp_2000, co2_2000, gdp_2015, co2_2015

Run these next three cells to check your answer. You should see the table get filled when you hover a point in either scatter plot.

In [19]:
# Use this cell to check your answer
app.run_server(port=8052)

Dash app running on http://127.0.0.1:8052/

# Next steps

After this initial exploration step, you've decided you would like to implement this data visualization as a bubble chart with an animation to transition between the two years. You also would like to change the axes display to be log-scaled. You will reuse some of this code and complete the rest of the code provided with this TP to make these changes.